### ISSUE TITLE
Change LogLevel on the fly?

### ISSUE THREAD

**Issue by K232** [tafuji/Xamarin-Forms-NLog-Sample#7]
Hi! Is it possible to change the loglevel on the fly, e.g. with a button in the app? The user should be able to manually enable the logging (= set loglevel to Debug), later on disable again (what would be the best regarding performance for that?) and then e.g. mail it to me. Would that be possible?
Many thanks!

**Comment by tafuji** [comment]
This code might be helpful.

https://gist.github.com/pmullins/f21c3d83e96b9fd8a720

**Comment by tafuji** [comment]
@K232 
I've updated the sample codes to change the loglevel.
Please see the codes.
I wish it would be helpful for you.

https://github.com/tafuji/Xamarin-Forms-NLog-Sample/blob/master/NLogSample/NLogSample.Logging/LoggingService.shared.cs#L76

**Comment by K232** [comment]
Thanks Tafuji!
